site_name: MONICA Documentation
site_description: Model for Nitrogen and Carbon in Agro-ecosystems
site_url: https://zalf-rpm.github.io/monica-documentation/
repo_url: https://github.com/zalf-rpm/monica-documentation
repo_name: monica-documentation

theme:
    name: material
    font: false
    palette:
      primary: green
      accent: light green
    features:
      - navigation.tabs
      - navigation.tabs.sticky
      - toc.integrate

extra:
  generator: false

markdown_extensions:
  - toc:
      toc_depth: 3
  - pymdownx.superfences
  - admonition
  - pymdownx.arithmatex:
        generic: true
  - attr_list

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Overview: index.md
  - User Guide:
      - Installation and Setup: 
          - Local installation: user_guide/Installation_and_Setup/local_installation.md
          - MONICA server: user_guide/Installation_and_Setup/monica_server.md
          - Docker setup: user_guide/Installation_and_Setup/docker_setup.md
          - Singularity Setup (HPC-friendly): user_guide/Installation_and_Setup/singularity_setup.md
          - HPC Setup: user_guide/Installation_and_Setup/hpc_setup.md
          - Rundeck setup: user_guide/Installation_and_Setup/rundeck_setup.md
          - Dependencies & Python version (requirements.txt): user_guide/Installation_and_Setup/dependencies_and_python.md
          - Troubleshooting Common Installation Issues: user_guide/Installation_and_Setup/troubleshooting_installation.md
      - Configuration Files:
          - Overview: user_guide/configuration_files/config_overview.md
          - sim.json: user_guide/configuration_files/config_sim_json.md
          - crop.json: user_guide/configuration_files/config_crop_json.md
          - site.json: user_guide/configuration_files/config_site_json.md
      - How to run: 
          - Running MONICA from Command Line (CLI): user_guide/how_to_run/command_line.md
          - Running MONICA in Docker: user_guide/how_to_run/docker.md
          - Running MONICA in CMD: user_guide/how_to_run/cmd.md
          - Running with Singularity: user_guide/how_to_run/singularity.md
          - Running on HPC: user_guide/how_to_run/hpc.md
          - Python API usage examples: user_guide/how_to_run.md
          - Using Online MONICA: user_guide/how_to_run/online_monica.md
      - Outputs and Visualisation: 
          - Understanding MONICA Outputs (CSV / JSON structure): user_guide/outputs_and_visualisation/monica_output.md
          - Visualization with Python/R (example scripts): user_guide/outputs_and_visualisation/visualisation.md
          - Example graphs: user_guide/outputs_and_visualisation/example_graphs.md
  - Parameter Reference and Calibration: parameter_reference_and_calibration.md
  - Model Science and Algorithm:
      - Soil Processes:
          - Overview: model_science/soil_processes/overview.md
          - Soil temperature: model_science/soil_processes/soil_temperature.md
          - Evaporation: model_science/soil_processes/evaporation.md
          - Soil moisture: model_science/soil_processes/soil_moisture.md
          - Soil frost: model_science/soil_processes/soil_frost.md
          - Snow: model_science/soil_processes/snow.md
          - Organic matter turn-over: model_science/soil_processes/organic_matter_turn-over.md
          - Nitrification and denitrification: model_science/soil_processes/nitrification_and_denitrification.md
          - Matter transport: model_science/soil_processes/matter_transport.md
      - Crop Processes:
          - Overview: model_science/crop_processes/overview.md
          - Photosynthesis: model_science/crop_processes/photosynthesis.md
          - Respiration: model_science/crop_processes/respiration.md
          - Assimilate partitioning: model_science/crop_processes/assimilate_partitioning.md
          - Ontogenesis: model_science/crop_processes/ontogenesis.md
          - Root growth: model_science/crop_processes/root_growth.md
          - Leaf area and ground coverage: model_science/crop_processes/leaf_area_and_ground_coverage.md
          - Transpiration: model_science/crop_processes/transpiration.md
          - N uptake: model_science/crop_processes/n_uptake.md
          - N concentration: model_science/crop_processes/n_concentration.md
          - Drought stress: model_science/crop_processes/drought_stress.md
          - Nitrogen deficiency: model_science/crop_processes/nitrogen_deficiency.md
          - Oxygen deficiency: model_science/crop_processes/oxygen_deficiency.md
          - Heat stress: model_science/crop_processes/heat_stress.md
          - Yield: model_science/crop_processes/yield.md
  - References and Further Reading:
      - Publications: references/publications.md
